name: Apply Branch Protection

on:
  workflow_dispatch: {}

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Apply branch protection using GitHub API
        env:
          REPO: ${{ github.repository }}
          BRANCH: main
        run: |
          GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          if [ -z "$GH_TOKEN" ]; then echo "No token available: ensure GITHUB_TOKEN is set"; exit 1; fi
          curl -X PUT -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/branches/$BRANCH/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["CI"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": false,
                "required_approving_review_count": 1
              },
              "restrictions": null
            }'

      - name: Confirm
        run: echo "Branch protection applied to $REPO:$BRANCH (if token had permissions)."
