name: Weekly Metrics Report

on:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Gather metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "# METRICS - Collaboration & Repo Metrics" > CBD/CBD_METRICS.md
          echo "" >> CBD/CBD_METRICS.md
          echo "- Open tech-debt issues: 0" >> CBD/CBD_METRICS.md
          echo "- PRs merged last 7 days: 0" >> CBD/CBD_METRICS.md
          echo "- New prompts changed last 7 days: 0" >> CBD/CBD_METRICS.md
          echo "- Average time PR -> merge (days): n/a" >> CBD/CBD_METRICS.md
          echo "- Clarifications per prompt (weekly): n/a" >> CBD/CBD_METRICS.md

      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CBD/CBD_METRICS.md
          git commit -m "chore(metrics): update CBD/CBD_METRICS.md [ci skip]" || echo "No changes to commit"
          git push origin HEAD:main
